name: fdl_api
description: The wrapper over FreedomLand API.
repository: https://github.com/fdl-mc/fdl-api-dart
version: 1.0.0

environment:
    sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
    pedantic: ^1.10.0
dependencies:
    http: ^0.13.3
